# config/elasticsearch/elasticsearch.yaml
cluster.name: streaming-cluster
node.name: node-1
network.host: 0.0.0.0
discovery.type: single-node

xpack.security.enabled: true
xpack.security.http.ssl.enabled: false

# Tối ưu cho streaming write
indices.memory.index_buffer_size: 30%
thread_pool.write.size: 8
thread_pool.search.size: 8