# grafana/provisioning/alerting/mute-timings.yaml
apiVersion: 1

muteTimeIntervals:
  - name: weekend-maintenance
    intervals:
      - weekdays: saturday-sunday
      - times:
          - start: "00:00"
            end: "23:59"