apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 05-airflow
  labels:
    app.kubernetes.io/part-of: data-platform
spec:
  project: default
  source:
    repoURL: "REPO_URL_PLACEHOLDER"
    path: "services/airflow"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: airflow
  syncPolicy:
    automated: {}
