apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 07-spark-jobs
  labels:
    app.kubernetes.io/part-of: data-platform
spec:
  project: default
  source:
    repoURL: "REPO_URL_PLACEHOLDER"
    path: "applications/spark-jobs"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: spark-jobs
  syncPolicy:
    automated: {}
