apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 99-team-apps
  labels:
    app.kubernetes.io/part-of: data-platform
spec:
  project: default
  source:
    repoURL: "REPO_URL_PLACEHOLDER"
    path: "applications/team-apps"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: team-apps
  syncPolicy:
    automated: {}
