version: '3.8'

services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: ${COMPOSE_PROJECT_NAME}_schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "${SCHEMA_REGISTRY_PORT}:8081"
    depends_on:
      - kafka
    networks:
      - data-pipeline-network

networks:
  data-pipeline-network:
    driver: bridge
